// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryAdjustment struct {
	AdjustmentID   uuid.UUID        `json:"adjustment_id"`
	ProductID      string           `json:"product_id"`
	PvID           string           `json:"pv_id"`
	AdjustmentType string           `json:"adjustment_type"`
	Quantity       int32            `json:"quantity"`
	Reason         string           `json:"reason"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type InventoryLevel struct {
	InventoryID uuid.UUID        `json:"inventory_id"`
	ProductID   string           `json:"product_id"`
	PvID        string           `json:"pv_id"`
	Stock       int32            `json:"stock"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ProductID   string           `json:"product_id"`
	VendorID    uuid.UUID        `json:"vendor_id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
	Discount    pgtype.Numeric   `json:"discount"`
	Stock       int32            `json:"stock"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProductImage struct {
	PiID      string           `json:"pi_id"`
	ProductID string           `json:"product_id"`
	PvID      string           `json:"pv_id"`
	ImageUrl  string           `json:"image_url"`
	Position  int32            `json:"position"`
	IsPrimary pgtype.Bool      `json:"is_primary"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ProductVariant struct {
	PvID       string           `json:"pv_id"`
	ProductID  string           `json:"product_id"`
	Sku        pgtype.Text      `json:"sku"`
	Price      pgtype.Numeric   `json:"price"`
	Stock      int32            `json:"stock"`
	Attributes []byte           `json:"attributes"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Vendor struct {
	VendorID    uuid.UUID        `json:"vendor_id"`
	VendorName  string           `json:"vendor_name"`
	ContactName string           `json:"contact_name"`
	ProductType []string         `json:"product_type"`
	Email       pgtype.Text      `json:"email"`
	Phone       pgtype.Text      `json:"phone"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
