// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateInventoryAdjustments(ctx context.Context, arg CreateInventoryAdjustmentsParams) (InventoryAdjustment, error)
	CreateInventoryLevels(ctx context.Context, arg CreateInventoryLevelsParams) (InventoryLevel, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateProductVariants(ctx context.Context, arg CreateProductVariantsParams) (ProductVariant, error)
	CreateVendors(ctx context.Context, arg CreateVendorsParams) (Vendor, error)
	DeletProduct(ctx context.Context, productID string) error
	DeleteProductImage(ctx context.Context, piID string) error
	DeleteProductVariantsByPvid(ctx context.Context, pvID string) error
	GetInventoryAdjustmentsByAdjustmentId(ctx context.Context, adjustmentID uuid.UUID) (InventoryAdjustment, error)
	GetInventoryAdjustmentsByPvid(ctx context.Context, arg GetInventoryAdjustmentsByPvidParams) ([]InventoryAdjustment, error)
	GetInventoryAdjustmentsByType(ctx context.Context, adjustmentType string) ([]InventoryAdjustment, error)
	GetInventoryLevelByInventoryId(ctx context.Context, inventoryID uuid.UUID) (InventoryLevel, error)
	GetInventoryLevelByPvid(ctx context.Context, arg GetInventoryLevelByPvidParams) ([]InventoryLevel, error)
	GetProductByProductId(ctx context.Context, productID string) (Product, error)
	GetProductByVendorID(ctx context.Context, vendorID uuid.UUID) ([]Product, error)
	GetProductImageByPiid(ctx context.Context, piID string) ([]ProductImage, error)
	GetProductImageByProductid(ctx context.Context, productID string) ([]ProductImage, error)
	GetProductImageByPvid(ctx context.Context, arg GetProductImageByPvidParams) ([]ProductImage, error)
	GetProductImagePrimary(ctx context.Context, arg GetProductImagePrimaryParams) ([]ProductImage, error)
	GetProductVariantsByProductId(ctx context.Context, productID string) ([]ProductVariant, error)
	GetProductVariantsByPvid(ctx context.Context, pvID string) (ProductVariant, error)
	GetProductVariantsByStatus(ctx context.Context, status string) ([]ProductVariant, error)
	GetVendorsByStatus(ctx context.Context, status string) ([]Vendor, error)
	GetVendorsList(ctx context.Context) ([]Vendor, error)
	UpdateInventoryLevel(ctx context.Context, arg UpdateInventoryLevelParams) (InventoryLevel, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
	UpdateVendorStatus(ctx context.Context, arg UpdateVendorStatusParams) (Vendor, error)
}

var _ Querier = (*Queries)(nil)
